import { format } from "date-fns"

export const RotaPrint = () => {
    return (
        <div className="opacity-0 -z-50 h-0">
            <div className="rota-print">
                <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni aperiam rerum, voluptas repellendus harum consectetur veritatis, nobis necessitatibus omnis tempora deserunt, animi sunt eligendi. Voluptates repellendus voluptatem, animi enim accusantium qui aliquid! Quod, iure quis. Quae laudantium repudiandae quam fugiat quod debitis sapiente ab id! Sapiente, suscipit, laboriosam cupiditate molestias quam consequatur voluptatem ratione, earum ipsa aspernatur deserunt quod quisquam ullam blanditiis incidunt voluptatum neque reiciendis mollitia aut nostrum officiis itaque iure molestiae. Tempora laborum vitae veniam, animi rerum maxime harum omnis rem pariatur id consectetur soluta odit? Vero, aperiam officiis recusandae explicabo eos itaque expedita consequuntur magni eius temporibus, id similique quas quo architecto assumenda. Voluptatum laudantium enim error doloribus veniam quidem! Quia maxime accusantium cumque ipsum aspernatur consectetur voluptatum quasi nulla delectus, itaque inventore ipsam? Culpa, ullam! Amet excepturi obcaecati nam tempora. Nobis velit quasi quos dolores deserunt vero similique quidem placeat odio nostrum facilis corrupti repellat recusandae, at nam, dolor facere ex aut ab hic minus. Quas voluptas accusamus, quam quasi quisquam cum consectetur odio possimus molestias labore nesciunt sed neque beatae distinctio! Ex quia natus, placeat molestias distinctio voluptates maxime, reiciendis vitae asperiores perspiciatis vel. Architecto quos consectetur repellat accusantium perspiciatis delectus, quo hic error tempora quia voluptas reprehenderit quae rem explicabo enim blanditiis commodi temporibus, aut repellendus facere placeat. Perspiciatis minima, ratione aut reprehenderit facilis labore eveniet ea ut vero. Incidunt dolorem ducimus nesciunt molestiae accusamus magnam velit deserunt corporis ut atque. Tenetur officia tempore nostrum provident, numquam eligendi! Odio et quaerat fugiat vitae suscipit dolor tenetur temporibus eius recusandae cum voluptatibus sit distinctio illo unde vel voluptatem, eveniet officiis repellendus in consectetur dolores minima? A natus dolorum numquam maxime velit eligendi provident, pariatur ut inventore tempora aliquam optio consectetur. Praesentium, quaerat neque quam, laudantium accusamus maxime non ut suscipit corporis id omnis? Quos, nulla! </h1>
                <p>{format(new Date(), 'ddMMyyyy')}</p>
            </div>
        </div>
    )
}